apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.whatifAgent.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.whatifAgent.name }}
  namespace: {{ .Values.whatifAgent.namespace }}
