# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

whatifAgent:
  name: whatif-agent
  image: saniyardev/whatif-agent:latest
  namespace: whatif-agent
  replicaCount: 1
  leaderElect: false

# LoadVariationRiskBalancing and TargetLoadPacking are not enabled by default
# as they need extra RBAC privileges on metrics.k8s.io.

plugins:
  default: [ "PrioritySort" ]
  enabled: [ "Whatif" ]
  disabled: []
